Mutable linear preference v3
Julienchilhagopian/J-Voting pull request #10
Opened 2020-05-28 17:28 UTC by leo-geindre

Bonjour,

Nous livrons la version finale de la classe MutableLinearPreference.
Nous avons besoin de celle-ci pour commencer le profil que nous allons mettre dans le GUI.
 
Thomas et Jade ont codé la classe.
J'ai effectué des vérifications et des propositions de changements et de nouvelles méthodes.

2020-05-31 21:50 UTC, oliviercailloux requested changes
Deux affectés max. SVP.
Précisez tous les contrats de MLP SVP, comme indiqué dans les remarques ci-dessous, à étendre aux autres méthodes. Je passerai ensuite à l’implémentation.

2020-05-31 21:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/FowardingGraph.java
> + * currently planned to be released as a general-purpose forwarding class.
Indiquez d’où vous copiez cette classe. Indiquer l’auteur est correct mais insuffisant : un lecteur ne sait pas nécessairement que cette personne n’est pas une personne de ce projet.

En outre, ce commentaire est bizarre, dans le contexte de ce projet. Il est censé dans son contexte original, lorsqu’il est clair que c’est Google Guava qui s’exprime, mais ce n’est pas le cas lorsqu’il est copié ici.

2020-05-31 21:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutableLinearPreference.java
> +	 * @param alternative that we're going to move in the preference
Doit-elle exister dans cette préférence ? Si oui, le préciser. Si non, préciser ce que fait cette méthode.

2020-05-31 21:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutableLinearPreference.java
> +	 * @param rank desired
Restrictions sur ce rang ? Numéroté à partir de zéro, ou un ?

2020-05-31 21:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutableLinearPreference.java
> +	 * @param alternative who belongs to the preference
Doit exister ?

2020-05-31 21:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutableLinearPreference.java
> +	 */
Manque tag @return et l’explication correspondante.

2020-06-04 09:28 UTC, oliviercailloux requested changes

2020-06-04 09:28 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutableLinearPreference.java
> +	public void changeOrder(Alternative alternative, int rank);
Il reste une légère ambiguïté dans ce contrat. S’il y a trois alternatives, et que je veux déplacer la première en dernière position, dois-je la mettre au rang 3 ou au rang 4 ? Le premier me semble plus naturel (le rang est le nouveau rang où l’alternative se trouvera), mais je ne pourrais pas être tout-à-fait sûr que vous avez suivi le même raisonnement. De même, il faudrait expliquer comment les autres alternatives se décalent : il me parait naturel que les alternatives intermédiaires se décalent toutes, mais on pourrait aussi penser que deux alternatives échangent simplement leurs positions. Et il serait agréable pour l’utilisateur se pouvoir être sûr de quelle alternative bouge de combien de rang et quelles alternatives ne bougent pas suite à cet appel.

2020-06-04 09:28 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutableLinearPreference.java
> +	 * @return true
Renvoyer une constante n’est aucunement utile. Le fait que la méthode renvoie qqch. introduit une complexité inutile, si cette valeur est non informative. Si vous voulez suivre le canevas général des collections (ce qui est sans-doute une bonne idée), il faut permettre d’appeler `remove` avec une alternative non existante, et rendre la valeur de retour informative. (Voir remove sur Set par exemple.)

2020-06-04 09:28 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutableLinearPreference.java
> +	public void swap(Alternative alternative1, Alternative alternative2);
Plus de précision et de rigueur seraient bien utiles pour la solidité et l’utilisabilité de cette interface. 

Peut-on donner en arguments deux fois la même alternative ? (Je propose : oui.) Si oui, préciser que dans ce cas la méthode n’a pas d’effet. Il pourrait être alors sympathique de renvoyer un booléen qui indique si la préférence a changé suite à l’appel (et faire en sorte qu’il soit clair pour le lecteur que c’est vrai ssi les alternatives passées sont différentes, moyennant la question de leur existence dans la préférence). 

Ces alternatives doivent-elles exister dans la préférence ? (Je propose : oui.)

2020-06-05 00:14 UTC, oliviercailloux requested changes

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutableLinearPreference.java
> +	public boolean swap(Alternative alternative1, Alternative alternative2);
La première phrase indique que les alternatives doivent exister dans cette préférence. Mais la dernière pourrait être comprise comme indiquant que cette méthode accepte qu’elles n’existent pas (auquel cas la valeur de retour est false). Pour éviter un malentendu, je suggère de préciser : or equivalently, false iff the specified alternatives are equal and contained in this preference.

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +
private ou package visible si nécessaire

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +			graph.removeNode(list.get(i));
Que donne le clear sur l’ensemble des nœuds dont nous avons discuté ?

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +		this.list = list;
Il faut faire une copie défensive de cette liste, sinon l’appelant peut la modifier sans votre permission en conservant une référence vers la liste qu’il vous fournit.

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +	 * @param list  is a LinkedList of alternatives representing the preference.
Ne pas mentionner une LinkedList ici.

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +				graph.putEdge(list.get(i), list.get(j));
Si votre structure n’est pas une random-access list (telle qu’une ArrayList), ceci sera terriblement inefficace. (Mais ce sera résolu par la copie défensive, si dans une ArrayList.)

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +		if (initRank > rank) { // swap à gauche
In English, please.

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutableLinearPreference.java
> +	public void changeOrder(Alternative alternative, int rank);
Vu les autres contrats, on s’attend à ce que ceci renvoie un booléen indiquant si l’ordre a changé (donc si l’alternative n’était pas déjà à ce rang). FUTURE

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +		Alternative a2 = alternative2;
Vous feriez preuve de gentillesse envers vos lecteurs en les nommant `best` et `worst`, par exemple.

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +			graph.putEdge(a2, a);
Il serait prudent de vérifier que les valeurs de retour sont vraies, pour échouer en cas de bug dans votre structure.

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +		}
Ceci semble inutilement compliqué. Pourquoi ne pas appeler simplement swap entre les deux positions (ou alternatives) à échanger, puisque swap implémente déjà cette logique de mise à jour du graphe point par point ? En outre, cette implémentation est très inefficace : O(m²) au lieu de O(m), à cause des multiples appels à indexOf qui seront effectués dans le swap, inutilement. FUTURE

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +		int initRank = list.indexOf(alternative);
Il faut que l’alternative existe dans la liste pour que cet appel soit censé, vous ne l’avez pas vérifié.

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +		LOGGER.debug("MutableLinearPreferenceImpl changeOrder");
Tant qu’on y est, il serait sympathique d’indiquer quelle alternative et quel rang, sans quoi la valeur de cette indication est très faible.

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +	 * @return an immutable set of all alternatives of the preference
Il n’est pas immuable puisqu’il reflète les changements. Il devrait même être modifiable, il me semble. De toute façon, cette documentation devrait aller sur l’interface, puisqu’elle n’est pas spécifique à cette implémentation, mais elle y est déjà je pense.

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +				!(alternatives.size() != graph.nodes().size() || !(alternatives.containsAll(graph.nodes()))),
Ceci devrait être garanti par cette classe, pas pouvoir échouer en fonction de l’état de quelque chose. Donc c’est un verify qui convient, si vous voulez le vérifier ici. Mais je dirais qu’il n’y a pas de raison spécifique de vérifier cet état ici, d’autant que cela prendra un temps non négligeable (O(m)).

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +		return Objects.hash(voter, graph, alternatives, list);
Le graphe et l’ensemble d’alternatives sont entièrement déterminés par la liste, inutile d’inclure tout ça dans le hash. FUTURE

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +				&& list.equals(mlp2.list);
Même remarque. Votre implémentation est en O(m²) alors que O(m) est possible. FUTURE

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +				+ ", list=" + list + "]";
Veuillez utiliser plutôt l’approche proposée en cours, par uniformité. Voir BP local design.

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +				return false;
Sauf erreur de ma part, ceci est inutilement complexe. Déléguer simplement l’appel suffirait.

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +			return hasChanged;
Bien trop complexe. Appelez simplement standardAddAll, comme la doc de ForwardingSet vous recommande. Voyez aussi le reste de la doc pour simplifications similaires.

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +	public class MutableLinearSetDecorator extends ForwardingSet<Alternative> {
Manquent la surcharge de retainAll et iterator (pour ce dernier, vous pouvez l’emballer simplement dans un décorateur d’itérateur non-modifiable, et mettre en FUTURE la tâche d’améliorer cette approche).

2020-06-05 00:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +	public class MutableLinearGraphDecorator extends ForwardingGraph<Alternative> {
Vérification faite, effectivement, les ensembles accessibles via ce délégué ne sont pas modifiables actuellement (https://github.com/google/guava/issues/3034), ce qui rend votre implémentation correcte actuellement. Cependant, cela n’est pas garanti par contrat, et donc pourrait changer.

Indiquez donc en FUTURE qu’il faudrait idéalement protéger les ensembles renvoyés via ce décorateur contre les modifications.

2020-06-05 00:14 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImplTest.java
> +		MutableGraph<Alternative> graph = GraphBuilder.directed().allowsSelfLoops(true).build();
Nommer ceci `expected` clarifierait nettement ce test.

2020-06-05 00:14 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImplTest.java
> +	}
Ajouter une variante de ce test qui modifie la liste après l’avoir passée au constructeur et qui vérifie que cela ne change pas votre structure. (Ce test échoue avec l’implémentation actuelle.)

2020-06-05 00:14 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImplTest.java
> +}
Ajouter au moins un test qui demande asGraph() puis modifie la préférence (par exemple en ajoutant une alternative et en modifiant l’ordre d’une autre paire et en en enlevant une quatrième) puis vérifie que le graphe obtenu précédemment reflète bien les changements.

Ajouter au moins un test qui récupère l’ensemble d’alternatives et le modifie, et qui vérifie que la structure est changée comme il se doit. (À moins qu’il y ait déjà un test de ce genre actuellement qui m’ait échappé.)

2020-06-11 15:58 UTC, daillet commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +			graph.removeNode(list.get(i));
Il n'existe pas de méthode clear() dans l'interface MutableGraph<N> de Guava permettant de clear l'ensemble des noeud. C'est pour cela que nous faisons une boucle avec removeNode()

2020-06-11 16:23 UTC, daillet commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +		}
Je m'excuse mais sauf erreur de ma part, changeOrder() n'échange pas 2 alternatives mais change de position l'une d'entre elle, impliquant un décalage de toutes celles entre l'ancienne position et la nouvelle. Cela revient effectivement à faire des swap successifs entre l'alternative à déplacer et son voisin, jusqu’à ce quelle atteigne le rang désiré.

2020-06-11 17:30 UTC, daillet commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +		this.list = list;
Sommes-nous d'accord que faire une copie défensif correspond à créer un decorator pour la liste ?

2020-06-11 17:35 UTC, daillet commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImplTest.java
> +	}
Comment faire pour que ce test n'échoue pas ? Devons nous override les méthodes qui peuvent casser la linéarité dans le decorator évoqué en tant que copie défensive plus haut ?

2020-06-13 12:30 UTC, daillet commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +		this.list = list;
update : pas de decorator mais quelque chose comme this.list = new ArrayList<>(list); dans le constructeur ?

2020-06-13 12:31 UTC, daillet commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImplTest.java
> +	}
Résolu grâce à la copie défensive

2020-06-13 12:37 UTC, jadenizard commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +	public class MutableLinearSetDecorator extends ForwardingSet<Alternative> {
Nous ne sommes pas parvenu à surcharger correctement ces deux méthodes. En effet, notre test sur retainAll() échoue sûrement à cause d'une implémentation imparfaite du decorator d'iterator.
A noter : nous n'avons pas implémenté nous même retainAll() mais avons suivi vos conseils et utilisé standardRetainAll déjà fourni ( qui utilise iterator).

2020-06-15 12:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutableLinearPreference.java
> +	 * @return true if the alternatives are contained in the preference and if the preference has changed after this call. Or equivalently, false if the specified alternatives are equal and contained in
FORMAT SVP

2020-06-15 12:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +	private static final Logger LOGGER = LoggerFactory.getLogger(MutableLinearPreferenceImpl.class.getName());
Utilisez SVP le canevas proposé au cours : `@SuppressW` pour le cas où on ne l’utilise temporairement plus ; `class` sans `getName()` car inutile. OPT.

2020-06-15 12:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +	public boolean changeOrder(Alternative alternative, int rank) {
Que se passe-t-il si je donne un rang supérieur au dernier rang existant (k+1 dans une liste de taille k) ? Et si le rang est largement supérieur (plus grand que k + 1) ? Un rang négatif ou nul ?

2020-06-15 12:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +		if(!(alternatives.contains(a))) {
Privilégier la structure inverse pour éviter que la majorité du code soit embarquée dans un if : renvoyer faux si on peut le faire facilement, puis poursuivre avec le cas « normal ». OPT.

2020-06-15 12:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +			graph.removeNode(list.get(i));
Ma question concernait `nodes().clear()`.

2020-06-15 12:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +				throw new IllegalArgumentException("There might be a bug in your stucture.");
Comment ça, un bug dans ma structure ? C’est votre structure qui semble avoir un bug dans ce cas. Lancez donc plutôt une `VerifyException`.

2020-06-15 12:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +			if(!(graph.removeEdge(best, a) && graph.putEdge(a, best) && graph.removeEdge(a, worst) && graph.putEdge(worst, a) )) {
Évitez cette construction : on peut croire qu’elle ne sert qu’à vérifier qqch., alors que les appels eux-même sont essentiels ; et elle rend la succession d’appels peu lisibles. Mieux vaut effectuer les appels un par un, affecter les résultats à des variables, et vérifier ensuite.

2020-06-15 12:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +		graph.putEdge(worst, best);
Même chose, ceci devrait renvoyer vrai et il faudrait le vérifier, au passage.

2020-06-15 12:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +	public class MutableLinearGraphDecorator extends ForwardingGraph<Alternative> {
Ceci ne semble pas avoir été fait.

2020-06-15 12:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +	public class MutableLinearSetDecorator extends ForwardingSet<Alternative> {
Les classes internes doivent être marquées `static`, pour indiquer que leur définition ne dépend pas de l’état de l’objet les incluant.

2020-06-15 12:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutableLinearPreference.java
> +	 * @return true if the alternatives are contained in the preference and if the preference has changed after this call. Or equivalently, false if the specified alternatives are equal and contained in
Ceci me semblerait plus clair : “true if the preference has changed after this call (and, thus, the alternatives are contained in this preference)”, plutôt que “true if the alternatives are contained in the preference and if the preference has changed after this call”. OPT.

2020-06-15 12:20 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +		this.list = list;
C’est bien ça.

2020-06-15 12:25 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +		}
Vous avez raison. Reste le problème de l’efficacité, cependant.

2020-06-15 12:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +				swap(temp, alternative);
swap appelle indexOf, une opération non élémentaire (O(m)), ce qui est conceptuellement inutile puisqu’on connait les positions de ces alternatives, à ce stade. L’efficacité de cette implémentation peut donc passer de O(m²) actuellement à O(m). On pourrait implémenter un `swapRanks`, qui serait utile par ailleurs. FUTURE.

2020-06-15 12:45 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImplTest.java
> +public class MutableLinearPreferenceImplTest {
Les classes de tests devraient s’appeler …Tests, par convention. FUTURE.

2020-06-15 12:45 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImplTest.java
> +	}
Je ne vois pas où ce test se trouve.

2020-06-15 13:11 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImplTest.java
> +		toTestPref.getAlternatives().addAll(c);
`addAll(ImmutableSet.of(…))` serait nettement plus lisible.

2020-06-15 13:11 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImplTest.java
> +		assertEquals(toTestPref, pref1);
Il faut améliorer la lisibilité de tous vos tests. On doit pouvoir s’assurer facilement que le test est correct, pour éviter le risque de se forger une fausse croyance qu’une partie du code est correcte (ce qui rend un débuggage particulièrement difficile). Entre autres, il ne faut pas intervertir ce qui est attendu et ce qui est obtenu effectivement, ce qui est fait dans ce `assertEquals` par exemple.

Ajoutez dans `AlternativeHelper` des champs du type `a1234list` (initialisés simplement en une ligne, en utilisant `ImmutableSet#asList()`) pour pouvoir créer votre résultat attendu en une seule ligne, cela améliorera nettement la lisibilité.

Il faut aussi placer vos tests dans un ordre cohérent, pour aider le lecteur. `testAddAlternative` doit, par exemple, venir avant `testAddAllDelegate`.

2020-06-15 13:11 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImplTest.java
> +		assertEquals(toTestPref, pref1);
Maintenant que votre implémentation de `equals` est mieux optimisée, ce test est incomplet. L’inconvénient de votre optimisation est qu’elle ne teste plus l’égalité des graphes (ce qui est effectivement non nécessaire si votre structure est cohérente, mais qui est précisément ce qu’on veut tester ici). Il faut donc ajouter à ce test une vérification explicite que le graphe de la structure après modification est bien égal au graphe de la structure attendue (`pref1`, ici).

2020-06-15 13:11 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImplTest.java
> +}
Je ne vois pas où le premier test mentionné ici se trouve.

2020-06-15 14:00 UTC, oliviercailloux requested changes
Veuillez ré-importer la config Eclipse (BP Eclipse) que je viens de modifier pour y ajouter un warning, et résoudre les warnings résultants en modifiant la visibilité de certaines méthodes de private en package. FUTURE.

Il me vient à l’esprit, suite à notre discussion d’aujourd’hui, que votre dernière itération UML devrait en priorité documenter en détail le fonctionnement de vos décorateurs (ou d’un décorateur en particulier, pris en exemple), pour aider vos successeurs.

Montrez-moi ce qui ne fonctionne pas avec un test qui échoue, concernant retainAll ou l’itérateur. Je ne suis pas sûr de comprendre, avec le code commenté en l’état, et avec l’appel à this.iterator au lieu du délégué.

2020-06-15 14:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfile.java
> +		Preconditions.checkNotNull(voterNames);
Il faut placer ces vérifications le plus profondément possible, pour être sûr qu’elles soient bien activées dans tous les chemins possibles. À déplacer dans le constructeur privé. FUTURE.

2020-06-15 14:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfile.java
> +		super();
Omettre ces appels au constructeur parent. FUTURE. (Ces deux commentaires, à répercuter partout.)

2020-06-15 14:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfile.java
> +     * @return true if the Voter is not already in the Profile
Et que fait donc cette méthode si le Voter est déjà dedans ? Rien ? Le préciser, et l’implémenter. (Actuellement, la structure pourrait se retrouver modifiée d’une façon qui va introduire un bug difficile à relever, dans ce cas.)

2020-06-15 14:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfile.java
> + * This class is Mutable. This is a strict Profile that will be used for the GUI model.
Préciser que ce profil contraint toutes les préférences à contenir les mêmes alternatives (si c’est bien votre intention).

2020-06-15 14:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfile.java
> +	 * Add a new voter to the Profile. The Voter takes a default Preference which is defined according the Set<Alternative> of the other preferences. It is added with a default name.
Il y a un problème logique. Une préférence ne peut pas être définie par un `set`, dont l’ordre n’est pas précisé. Il faut que cet ordre soit déterministe, pour éviter les surprises. Vous pourriez par exemple ordonner par ordre alphabétique de nom.

2020-06-15 14:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfile.java
> +     * @return true if the Voter is in the Profile
L’implémenter, donc.

2020-06-15 14:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfile.java
> +		voterNames.remove(v);
En profiter pour vérifier la cohérence de votre structure : ce Voter devait être dans le profil ssi il était aussi dans les noms.

2020-06-15 14:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfile.java
> +     * @return true if the name has changed after this call
…

2020-06-15 14:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfile.java
> +	 * @param a a non existing alternative
Vérifier que cette alternative n’y était pas déjà, donc.

2020-06-15 14:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfile.java
> +     * @return true
Cf. discussion précédente.

2020-06-15 14:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfile.java
> +	public Set<Voter> getVoters() {
Documenter comment cet ensemble réagit aux modifications, et implémenter en conséquence. (Éventuellement, faites au plus simple pour le moment en utilisant `Collections.unmodifiable…` et laissez en FUTURE les propositions plus subtiles.)

2020-06-15 14:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfile.java
> +	public static MutableStrictProfile given(Map<Voter, MutableLinearPreference> profile, BiMap<Alternative, String> alternativeNames, BiMap<Voter, String> voterNames) {
Ajouter une factory `empty()` qui renvoie un profil sans électeurs ni alternatives, pour démarrage facile.

2020-06-15 14:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfile.java
> +	public Set<Alternative> getAlternatives() {
Que peut-on faire avec l’ensemble renvoyé ? (Envisagez pour le moment de renvoyer une simple copie pour faire simple et laisser plus complexe pour plus tard.)

2020-06-15 14:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfile.java
> +		return it.next().getValue().getAlternatives();
Il serait plus élégant de ne pas passer par un `entrySet` alors que vous êtes intéressé par la valeur uniquement.

Ce code échoue si le profil est vide au lieu de renvoyer un ensemble vide. (Ajouter un test unitaire pour ce cas.)

2020-06-15 14:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfile.java
> +	public MutableLinearPreference getPreference(Voter v) {
Ceci permet de casser votre garantie d’ensembles d’alternatives égaux pour tous, puisqu’on peut modifier la préférence renvoyée. Il faut enrober cet objet pour éviter la modification de l’ensemble d’alternatives (mais permettre la modification de l’ordre).

2020-06-15 14:00 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfileTest.java
> +		alternativeNames.put(a2, "Pâte au saumon");
« Pâtes au saumon » aurait une meilleure chance face aux autres alternatives.

2020-06-15 14:00 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfileTest.java
> +		MutableLinearPreference mlp3 = MutableLinearPreferenceImpl.given(v3, list3);
Raccourcir, comme indiqué par ailleurs.

2020-06-15 14:00 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfileTest.java
> +		Alternative a3 = Alternative.withId(3);
Utiliser AlternativesHelper et VoterHelper pour éliminer ceci.

2020-06-15 14:00 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfileTest.java
> +		alternativeNames.put(a3, "Fondue Savoyarde");
Utiliser le constructeur d’ImmutableBiMap adéquat pour raccourcir à une instruction.

2020-06-15 14:00 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfileTest.java
> +		profile.put(v3, mlp3);
Raccourcir.

2020-06-15 14:00 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfileTest.java
> +		//assertEquals(set, toTest.getAlternatives());
?

2020-06-15 14:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +//			return new MutableLinearIteratorDecorator(this.iterator());
J’imagine que vous voulez dire, `delegate.iterator()`.

2020-06-15 14:00 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImplTest.java
> +		//assertEquals(toTestPref, pref1);
Veuillez laisser le code non commenté, même (et surtout) s’il ne fonctionne pas et que vous voulez m’interroger à son sujet : ça permet de voir le test échouer dans GH WF et de tester plus facilement chez moi ; et ça évite qu’on l’intègre par mégarde en l’état et que le problème passe inaperçu.

2020-06-22 12:49 UTC, daillet commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +			graph.removeNode(list.get(i));
graph.nodes().clear(); renvoie une UnsupportedOperationExeception, nous n'arrivons pas à faire mieux que la boucle avec le removeNode().

2020-06-22 12:59 UTC, daillet commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImplTest.java
> +	}
Ce test est présent à la fin de testAddAlternative().  Pref1 est créée avec list1 puis l'on modifie list1 en lui ajoutant a6 et on vérifie que pref1 n'a pas changé.

2020-06-22 13:21 UTC, daillet commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImplTest.java
> +}
Ce premier test est ajouté  la fin de testSwap(). On récupère le graph de toTestPref dans une variable expected puis on ajoute une alternative a6 à toTestPref, on swap a3 et a4 et on enlève a1. Enfin on vérifie que expected obtenue précédemment est bien égale à toTestPref.asGraph().

2020-06-22 13:25 UTC, daillet commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +	public boolean changeOrder(Alternative alternative, int rank) {
Nous proposons de lever une exception dans le cas ou le rang demandé est en dehors des rangs possibles.

2020-06-25 09:41 UTC, daillet commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/MutableStrictProfileTest.java
> +		MutableLinearPreference mlp3 = MutableLinearPreferenceImpl.given(v3, list3);
Nous avons réduit au maximum la taille des test en créant des classes "Helper" et en utilisant les constructeurs d'ImmutableMap. Cependant, nous avons gardé la méthode createMSP ToTest() en l'état car étant amené a changer, la construction grâce à des ImmutableMap ne semblait pas convenir.

2020-06-30 18:36 UTC, merged