Guiv2
Julienchilhagopian/J-Voting pull request #14
Opened 2020-06-23 16:46 UTC by jadenizard

Bonjour, 

Cette PR traite uniquement l'ajout d'alternative dans une MLP affichée en GUI. 
L'editionController s'occupe bien de construire le listener (si le nom de méthode buildAddAlternativeBehavior ne vous convient pas on est preneur de suggestions).
L'édition view s'occupe bien d'ajouter un SelectionListener sur tous les boutons d'ajout d'alternative (pour l'instant il y en a qu'un seul).
Dans l'état actuel du GUI nous avons pas vu l'intérêt d'une méthode refresh qui rafraîchit la vue. On pense qu'elle appellerait seulement displayAlternatives. Mais dites-nous si quelque chose nous échappe. 
Merci !

Développeurs : Julien et Léo
SMPO : Jade

2020-06-24 07:54 UTC, oliviercailloux requested changes
N’avais-je pas déjà approuvé MLP par exemple ? Veuillez vous assurer que je voie uniquement les changements pertinents, ou dites-moi si je fais erreur.

2020-06-24 11:16 UTC, Julienchilhagopian commented
Il n'y a pas encore de MLP dans master. L'autre groupe fait le maximum pour converger la PR#10. 
En attendant, le GUI doit lui aussi avancer malgré l'usage d'une MLP comme model. Pour cela, nous aimerions connaitre votre avis sur la partie gui de cette PR pour vérifier que l'on soit sur la **même longueur d'onde concernant MVC**.

Nous sommes conscient que cette PR ne peut pas être acceptée sans une MLP validée. Mais ce serait pratique si possible d'avoir déjà un retour sur les classes du package **profileManipulationGUI** de cette PR. 

Merci

2020-06-24 21:32 UTC, oliviercailloux requested changes
Ok, vous faites bien, dans ce cas.

2020-06-24 21:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/VisualizationView.java
> +		this.tabfolder = mainTabFolder;
checkNotNull

2020-06-24 21:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionView.java
> +		this.tabfolder = mainTabFolder;
checkNotNull

2020-06-24 21:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionView.java
> +	public void displayVoters(String voterName) {
Pourquoi ce pluriel ?

2020-06-24 21:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionView.java
> +	public void displayVoters(String voterName) {
Ce nom de méthode est trompeur, puisqu’elle ajoute un contrôle. Le nom suggère qu’appeler plusieurs fois la méthode avec le même paramètre n’a pas d’effet au-delà du premier appel, ce qui est faux. `addVoter` conviendrait peut-être mieux ?

2020-06-24 21:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionView.java
> +			alt.setText(a.toString());
?

2020-06-24 21:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionView.java
> +	 *               Preference..
set ou list ?

2020-06-24 21:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionView.java
> +		editionTab.setControl(mainComposite);
¿

2020-06-24 21:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionView.java
> +	public Map<Button, Text> getAddAlternativeControls() {
Si possible, il serait plus élégant de conserver les contrôles privés et d’obliger le contrôleur à donner des ordres de haut niveau plutôt que l’autoriser à manipuler directement les contrôles.

2020-06-24 21:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionView.java
> +	public void cleanAltContent() {
Il serait plus élégant de permettre uniquement de remplacer un contenu par un autre. Tout effacer ne sert à rien si ce n’est pas pour remplacer par autre chose, j’imagine.

2020-06-24 21:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/View.java
> +	public EditionView buildEditionView() {
Il serait plus clair d’éviter de donner à l’utilisateur la possibilité de créer autant d’ editionView qu’il souhaite, car cela n’a pas de sens. Il faut plutôt en créer une et une seule à l’initialisation, et remplacer cette méthode par `getEditionView`.

2020-06-24 21:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionController.java
> +		String voterName = this.controller.getModel().getVoter().toString();
?

2020-06-24 21:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionController.java
> +		Integer textFieldId = Integer.parseInt(textField.getText());
Il est plus simple et plus sûr de demander à la bibliothèque de renvoyer un entier et d’attraper l’exception si ce n’est pas un entier pour alors agir de manière appropriée.

2020-06-24 21:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionController.java
> +		Alternative newAlt = Alternative.withId(textFieldId);
Il me semblait qu’on avait envisagé de donner des noms aux alternatives et une map dans votre modèle entre les ids (entiers) et les noms (strings). Si vous voulez simplifier, ok, mais je ne suis pas sûr que ce soit plus simple (de par le fait que l’utilisateur peut ne pas entrer un entier).

2020-06-24 21:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionController.java
> +		editionView.displayAlternatives(controller.getModel().getAlternatives());
Logique fragile : si on oublie d’appeler clean avant display, on obtient n’importe quoi. Et on ne voit pas pourquoi il serait raisonnable d’appeler display sans avoir appelé clean juste avant. Il faut donc que display implique clean.

2020-06-25 06:51 UTC, Julienchilhagopian commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionView.java
> +	public void cleanAltContent() {
Léo je prends ça

2020-06-25 06:51 UTC, Julienchilhagopian commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionView.java
> +	public Map<Button, Text> getAddAlternativeControls() {
Léo je prends ça

2020-06-25 06:53 UTC, Julienchilhagopian commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionController.java
> +		Alternative newAlt = Alternative.withId(textFieldId);
Léo on en discute de ça. Pour info cette feature n'est possible que si on a un profile comme model. Or, pour l'instant on a qu'une MLP comme model

2020-06-25 06:53 UTC, Julienchilhagopian commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionController.java
> +		editionView.displayAlternatives(controller.getModel().getAlternatives());
Léo je prends ça

2020-06-27 18:42 UTC, Julienchilhagopian commented
Bonjour Monsieur, 
Merci pour vos commentaires. Nous avons livré toutes ces corrections.
Deux précisions : 
- Nous avons décidé de ne pas rethrow l'exception présente dans le try catch qui vérifie que le nom de l'alternative est bien un entier pour éviter d'impacter l'expérience utilisateur.
- Nous ne pouvons pas utiliser une BiMap Alternative/noms pour l'instant car cette fonctionnalité sera disponible que lorsque le MutableStrictProfile sera utilisé comme model et non la MLP actuelle.

2020-06-27 23:05 UTC, oliviercailloux requested changes
Je propose d’attendre, à ce stade où cette PR devient raisonnablement proche de l’acceptation j’imagine, la fusion de la PR dont elle dépend. Dites-moi si cette stratégie vous semble poser problème.

2020-06-29 07:20 UTC, oliviercailloux requested changes
Cf. Guiv3.

2020-06-29 07:25 UTC, closed without merging