Guiv3
Julienchilhagopian/J-Voting pull request #19
Opened 2020-06-28 19:58 UTC by jadenizard

Bonjour Monsieur, 

Cette PR part de l'état du GUI corrigé de la PR #14. Elle dépend toujours de la MLP mais comme on avait en stock la fonctionnalité de suppression d'alternative on a décidé de vous la soumettre. 
Donc on peut dans cette PR supprimer une alternative dans le GUI. En outre, nous avons corrigé le problème de décalage des colonnes rencontré sur le layout.

Merci. 

DEV : Julien/Léo 
SMPO : Jade

2020-06-29 07:19 UTC, oliviercailloux requested changes
Dois-je reviewer Guiv2 ET Guiv3 ? Merci de fermer l’une des deux ou expliquer…

2020-06-29 07:24 UTC, Julienchilhagopian commented
Bonjour, 
Vous pouvez vous concentrer sur cette PR GuiV3. 
On ferme la PR Guiv2.
Merci

2020-06-30 13:12 UTC, oliviercailloux requested changes
Comptez-vous fusionner la PR #18 ? Pour rappel, c’est nécessaire pour l’intégrer à votre présentation finale, si c’est votre intention.

2020-06-30 19:10 UTC, Julienchilhagopian commented
Bonjour, 
Nous avons fusionné la PR #18. 
Cette PR Guiv3 n'affiche donc que les différences liées au développement du GUI.
Merci.

2020-06-30 22:08 UTC, oliviercailloux approved these changes

2020-06-30 22:08 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profileManipulationGUI/EditionController.java
> +		}
Il serait plus élégant de limiter le try-catch à la conversion (une ligne de code). OPT.

2020-07-01 06:53 UTC, merged