Mutable linear preference
Julienchilhagopian/J-Voting pull request #3
Opened 2020-04-20 16:16 UTC by Julienchilhagopian

Pierre&Leo

Our goal on this iteration is to create a MutableLinearPreferenceImpl class and the interface which implements MutableLinearPreference. This class aims to work on mutable and linear preferences. The number of alternatives can thus evolve, one alternative cannot be equal to another and all the alternatives are comparable two by two.

To do this, we have implemented several methods in this class :

- Constructor: Takes as parameters, a voter and a graph of alternatives. Verifies that this graph has no cycle, that each alternative is comparable two by two and that the alternatives are not equal. This returns a MutableLinearPreference.

- changeOrder method: Replaces the old graph with the one taken as parameter. This method verifies that this network has no cycle, that all alternatives are comparable two by two and that the alternatives are not equal.

- deleteAlternative method: Takes the alternative to be deleted as a parameter and deletes this alternative with its dependencies.

- addAlternative method : Adds the alternative provided as parameter. Also adds a link between the "lowest" ranked alternative and the new alternative.

- getAlternatives method: Returns an immutable set of preference alternatives.

- getVoter method : Returns a voter.

- asGraph method: Returns the transitive closure of this mutable and linear graph.

We also tested these different methods in a class of tests called MutableLinearPreferenceImplTest :
- testAsGraph()
- testAddAlternative()
- testDeleteAlternative()
- testChangeOrder()
- testGetAlternatives()

2020-04-20 19:47 UTC, oliviercailloux requested changes
Je ne suis pas convaincu par l’intérêt de MLP telle que cette interface est définie actuellement. Son implémentation est beaucoup trop basée sur le graphe, et ne permet donc pas à l’utilisateur une manipulation facile. Votre approche oblige l’utilisateur, en fait, à manipuler un graphe, et ajouter et enlever des tas d’arêtes chaque fois qu’il veut changer une alternative de position (à moins que quelque chose m’ait échappé). On s’attend, au contraire, à une exploitation de cette situation très particulière et offrant plus de facilité qu’est la préférence complète. Quelques exemples de méthodes utiles : permettre d’inverser deux alternatives de position ; indiquer qu’on veut enlever l’alternative en position i ; qu’on veut ajouter une alternative en position i ; qu’on veut mettre l’alternative i en position k…

2020-04-20 19:47 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutableLinearPreference.java
> +public interface MutableLinearPreference extends Preference {
Préciser dans la javadoc si l’ensemble des alternatives considéré est fixe (si on démarre avec "a", "b", "c", on ne peut jamais ajouter "d") et on peut uniquement changer l’ordre ; ou si on peut changer l’ordre et le nombre des alternatives et les alternatives elles-même.

2020-04-20 19:47 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +	protected Voter voter;
Voyez SVP BP Style Formatting.

2020-04-20 19:54 UTC, oliviercailloux requested changes

2020-04-20 19:54 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +			throw new IllegalStateException("An alternative must not be deleted from the set");
Utiliser checkState SVP.

2020-04-20 19:54 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +        	if (graph.successors(a).size() == 0)
Si ce test sert pour le cas où `a` est déjà dans le graphe avant l’ajout, il ne faut pas le mettre dans la boucle. Sinon, commentez SVP.

2020-04-20 19:54 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +		return ImmutableGraph.copyOf(Graphs.transitiveClosure(graph));
Ceci est horriblement coûteux en terme de performances. Il faut maintenir la fermeture transitive à jour. (Ce que vous faites, d’ailleurs, si je ne me trompe, auquel cas, inutile de la re-calculer ici.) Il faut renvoyer un graphe non modifiable, et non une copie (cf. contrat de cette méthode).

2020-04-20 19:54 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +    	this.graph = prefGraph;
On s’attend à ce que votre structure principale soit une liste, non un graphe. Cela permettrait de récupérer beaucoup plus rapidement, par exemple, la ième alternative, ou de changer les positions. (Il faut alors construire le graphe seulement à la demande, pour de meilleures performances.)

2020-04-22 17:22 UTC, oliviercailloux requested changes

2020-04-22 17:22 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImplTest.java
> +        assertEquals(Graphs.transitiveClosure(graph), pref.asGraph());
Ajoutez les boucles explicitement SVP (sans faire appel à transitiveClosure), pour qu’on puisse voir facilement en lisant le code quel est le graphe attendu (sans avoir à calculer mentalement la fermeture).

Même chose pour les autres tests.

2020-04-22 17:22 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImplTest.java
> +        pref.deleteAlternative(a3);
Il serait plus intéressant de tester uniquement le delete (plutôt que add puis delete), il me semble, à moins qu’une subtilité m’échappe.

2020-05-04 11:29 UTC, leo-geindre commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutableLinearPreferenceImpl.java
> +		return ImmutableGraph.copyOf(Graphs.transitiveClosure(graph));
La classe AsUnmodifiableGraph dont vous nous avez parler est dans la bibliothèque JGraphT.
Or nous travaillons sur Google Guava de puis le début. Il ne me semble pas que ça soit une bonne idée d'utiliser cette nouvelle bibliothèque car les graphes ne sont pas formés de la même façon. Etes-vous d’accord ?
Dans Google Guava, il n'y a pas de classe ressemblant à "UnmodifiableGraph". Le seul moyen que j'ai trouvé pour donner un accès en lecture est le "CopyOf". Doit-on rester sur cette syntaxe qui ne convient pas totalement au contrat ?
Sinon pour coller au contrat, on peut retourner l'attribut graph, mais cela poserait des problème car il serait modifiable.

2020-06-30 18:36 UTC, merged